// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupRolloutPrefs.browser.cache.offline.storage.enable", false);
user_pref("app.normandy.startupRolloutPrefs.network.dns.dns_query_single_label", false);
user_pref("app.normandy.user_id", "907a9269-0ec4-4eff-9298-7f6372543b56");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1607648302);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1607648300);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.ctrlTab.previews", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1607648298);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 102);
user_pref("browser.newtabpage.activity-stream.impressionId", "{e66e041e-524e-4a3a-8c49-550b977e5a13}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1607648302008");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1607669902008");
user_pref("browser.search.region", "SG");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1607648300");
user_pref("browser.slowStartup.averageTime", 2822);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20201112153044");
user_pref("browser.startup.homepage_override.mstone", "83.0");
user_pref("browser.startup.lastColdStartupCheck", 1607648299);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1607648303094");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "83.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "0be49a7336c44344a07355d8ec3c7f6c");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "83.0");
user_pref("extensions.lastPlatformVersion", "83.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"748c845b-529f-43c0-9bf7-58ffad417311\",\"formautofill@mozilla.org\":\"c271d772-7594-464e-ab98-79bea8214868\",\"screenshots@mozilla.org\":\"989d6816-53a6-4e5e-b552-25bee2925875\",\"webcompat-reporter@mozilla.org\":\"adde1ce1-0cb7-4c3b-802f-134a4531cbe3\",\"webcompat@mozilla.org\":\"1cef816b-0b6a-4422-ba1f-56f6aa928914\",\"default-theme@mozilla.org\":\"aaae116d-4714-4b12-a281-499c538879e5\",\"google@search.mozilla.org\":\"1ffc2f62-cb46-4bdb-84e5-705d61f53ec6\",\"amazondotcom@search.mozilla.org\":\"6842669b-5f1e-4cb5-88d6-a04eb1736a4c\",\"wikipedia@search.mozilla.org\":\"ef0e08d3-2054-45d3-a573-796139729301\",\"bing@search.mozilla.org\":\"2071735d-dc9e-46c4-a3d3-00e9bad66f0e\",\"ddg@search.mozilla.org\":\"150b36a4-91e1-413a-acf8-2c14aa5896c2\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.state.flash", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "c5e46fab-2b68-4b1f-a5a7-54139837ba61");
user_pref("security.sandbox.plugin.tempDirSuffix", "7c80349a-d4d7-4d31-b865-2c09200088cc");
user_pref("signon.usage.hasEntry", false);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("toolkit.startup.last_success", 1607648295);
user_pref("toolkit.telemetry.cachedClientID", "ad27059f-9c88-4085-a7c0-23c04422b805");
user_pref("toolkit.telemetry.previousBuildID", "20201112153044");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
