// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "c912c909-5918-4b17-acad-4412b8a9b719");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1612964323);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1612964323);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.defaultLocation", "unfiled");
user_pref("browser.cache.disk.amount_written", 0);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.ctrlTab.previews", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1581920457);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.migration.version", 104);
user_pref("browser.newtabpage.activity-stream.impressionId", "{7418a9cb-2a07-4a9b-8829-6af39e749284}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1612964323722");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1612985923722");
user_pref("browser.search.region", "SG");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210118153634");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1612964323");
user_pref("browser.slowStartup.averageTime", 1762);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20210118153634");
user_pref("browser.startup.homepage_override.mstone", "85.0");
user_pref("browser.startup.lastColdStartupCheck", 1612964322);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1581920459601");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "85.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.peppermint.bookmarksProcessed", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "80cc2707e1284b528ff331dd9026fb2b");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210118153634");
user_pref("extensions.lastAppVersion", "85.0");
user_pref("extensions.lastPlatformVersion", "85.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"b94780e7-48aa-4511-ad20-be8dd7db92b7\",\"formautofill@mozilla.org\":\"88c5de1c-a801-41f5-a018-66f2e89e8b4c\",\"screenshots@mozilla.org\":\"ae1815ac-6fdb-4699-9723-0f4e3a3998a8\",\"webcompat-reporter@mozilla.org\":\"8af05d92-a7c3-46d6-aa87-cf50a2299abe\",\"webcompat@mozilla.org\":\"80e1a815-2a0e-4875-bb04-3f4dd6e860f2\",\"default-theme@mozilla.org\":\"358a25e1-c457-4f9f-adab-4a2e37891fe1\",\"google@search.mozilla.org\":\"e83a1a08-dfd7-4176-aa69-ffa312b8b09e\",\"amazondotcom@search.mozilla.org\":\"ec51d3bd-0515-403c-8af8-9b83c33e72c3\",\"bing@search.mozilla.org\":\"921d918e-80e1-4308-a574-02e8a216e62a\",\"ddg@search.mozilla.org\":\"59eb9047-01a4-454c-93f6-ffa7f89df3df\",\"ebay@search.mozilla.org\":\"5634c700-887a-4159-9e16-1ec323bfadc5\",\"twitter@search.mozilla.org\":\"58cbb1db-7070-4ba4-bfee-905e020f58b9\",\"wikipedia@search.mozilla.org\":\"409b373f-b557-4fc0-be0b-07067ddf496e\"}");
user_pref("general.smoothScroll.mouseWheel.migrationPercent", 0);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.flash.lastmod_hi", 369);
user_pref("plugin.flash.lastmod_lo", 2078429776);
user_pref("plugin.state.flash", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "bb0f2dd8-d706-40c4-b62e-e92c776f69db");
user_pref("security.sandbox.plugin.tempDirSuffix", "c4bfd270-af33-4263-becf-cd9d36152caf");
user_pref("signon.importedFromSqlite", true);
user_pref("signon.usage.hasEntry", false);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("toolkit.startup.last_success", 1612964319);
user_pref("toolkit.telemetry.cachedClientID", "3d3a49b8-74bc-4799-880f-7e33ee668dbe");
user_pref("toolkit.telemetry.previousBuildID", "20210118153634");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
