// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.last_seen_buildid", "20200217142647");
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.user_id", "bbea1359-a562-4725-91d8-bf87d03a6ce1");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1582816334);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1582816307);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.amount_written", 0);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.ctrlTab.previews", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1582816304);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 91);
user_pref("browser.newtabpage.activity-stream.impressionId", "{e6f1098d-c34c-47c7-886a-782a1f08f422}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1582816308600");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1582819908600");
user_pref("browser.search.region", "SG");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200217142647");
user_pref("browser.slowStartup.averageTime", 2140);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200217142647");
user_pref("browser.startup.homepage_override.mstone", "73.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1582816348);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1582816306582");
user_pref("distribution.iniFile.exists.appversion", "73.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.peppermint.bookmarksProcessed", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "3351206404db4e93ae1c7a8b8b3c10d5");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200217142647");
user_pref("extensions.lastAppVersion", "73.0.1");
user_pref("extensions.lastPlatformVersion", "73.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"38f3b652-be66-41c7-82cc-af208ef10fbf\",\"formautofill@mozilla.org\":\"9d49d173-0112-4881-b0d0-39ae9c26e69f\",\"screenshots@mozilla.org\":\"e7e1e4e5-1f1e-4d75-a774-9bab4a431c7b\",\"webcompat-reporter@mozilla.org\":\"8f0625ea-74a1-4ac7-946c-be765fdb2263\",\"webcompat@mozilla.org\":\"162037fc-e52e-4934-a88b-4390b5e4f53d\",\"default-theme@mozilla.org\":\"4ce5dc62-ea73-4a4a-98c7-f416ded8827a\",\"google@search.mozilla.org\":\"4ed5ea04-6e35-48a7-9a94-69ebef5b2e27\",\"amazondotcom@search.mozilla.org\":\"ecddfbde-f7e6-4de6-ab9b-1a348c8eb76f\",\"bing@search.mozilla.org\":\"a87f51ad-67f7-4632-affe-d0c38d143159\",\"ddg@search.mozilla.org\":\"c2058f50-3e5f-4717-be80-f5e66d2d3a52\",\"ebay@search.mozilla.org\":\"e3e5ff18-1b3a-427b-ac9e-770a285b4816\",\"twitter@search.mozilla.org\":\"13f087d6-a593-4c7f-9d15-d8c6bb2b9c65\",\"wikipedia@search.mozilla.org\":\"16fbac71-1b1d-4346-952f-27deed4dd91b\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.flash.arch", "x86_64-gcc3");
user_pref("plugin.flash.blockliststate", 0);
user_pref("plugin.flash.desc", "Shockwave Flash 32.0 r0");
user_pref("plugin.flash.lastmod_hi", 368);
user_pref("plugin.flash.lastmod_lo", 930818072);
user_pref("plugin.flash.path", "/usr/lib/flashplugin-installer/libflashplayer.so");
user_pref("plugin.flash.version", "32.0.0.330");
user_pref("plugin.state.flash", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "063cc2a8-a129-4774-bdba-2656277e7dfb");
user_pref("security.sandbox.plugin.tempDirSuffix", "91370768-554a-4c56-b07f-54e6fa118106");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("toolkit.startup.last_success", 1582816346);
user_pref("toolkit.telemetry.cachedClientID", "61193a5e-a2bc-4bc2-9125-9064e5dab412");
user_pref("toolkit.telemetry.previousBuildID", "20200217142647");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
