// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.startupRolloutPrefs.devtools.responsive.metaViewport.enabled", true);
user_pref("app.normandy.startupRolloutPrefs.extensions.blocklist.useXML", false);
user_pref("app.normandy.user_id", "d98e7407-2229-40ac-9db9-5cb247c284ca");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.amount_written", 0);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.ctrlTab.previews", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1580924262);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 89);
user_pref("browser.newtabpage.activity-stream.impressionId", "{11486fb3-581f-43ff-9c9b-6ea2df41af0d}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1580924266371");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1580927866371");
user_pref("browser.search.region", "SG");
user_pref("browser.slowStartup.averageTime", 2973);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200117190643");
user_pref("browser.startup.homepage_override.mstone", "72.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1580924263);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1580924264853");
user_pref("distribution.iniFile.exists.appversion", "72.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.peppermint.bookmarksProcessed", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "d69f356f4c55428aadd7c96100cffb57");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "72.0.2");
user_pref("extensions.lastPlatformVersion", "72.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"631c1358-d381-4dbe-a417-755119654b90\",\"formautofill@mozilla.org\":\"f4b541ca-de1b-4b8d-9266-656c8bc39653\",\"screenshots@mozilla.org\":\"a2e3b7ae-a935-4a8d-bb6c-f5c7b9aafaa6\",\"webcompat-reporter@mozilla.org\":\"b999ebfd-0c52-4379-9c2b-e7523a7c9f47\",\"webcompat@mozilla.org\":\"7f29b1cd-0a1f-422a-9dc1-224bcac4bea5\",\"default-theme@mozilla.org\":\"e9b7c854-687c-4098-ba05-08e96ed849b2\",\"google@search.mozilla.org\":\"c2219aa3-34ac-4405-8b85-caf6a5cb13ce\",\"amazondotcom@search.mozilla.org\":\"0560da2b-ec6e-4c7e-a0e3-e463554f0419\",\"bing@search.mozilla.org\":\"23680010-4f4e-4d0c-80fb-9b29675b2629\",\"ddg@search.mozilla.org\":\"aefc8924-7d6b-48ea-a704-8c87ccda58de\",\"ebay@search.mozilla.org\":\"0b7081c1-5232-4f23-8bcd-0ef106ce7b8a\",\"twitter@search.mozilla.org\":\"d0765374-406d-4cd3-b65f-bc1dd4f9c79f\",\"wikipedia@search.mozilla.org\":\"34ed2059-05e1-4756-a934-bd56f5fcc951\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.flash.arch", "x86_64-gcc3");
user_pref("plugin.flash.blockliststate", 0);
user_pref("plugin.flash.desc", "Shockwave Flash 32.0 r0");
user_pref("plugin.flash.lastmod_hi", 367);
user_pref("plugin.flash.lastmod_lo", -1406118928);
user_pref("plugin.flash.path", "/usr/lib/flashplugin-installer/libflashplayer.so");
user_pref("plugin.flash.version", "32.0.0.314");
user_pref("plugin.state.flash", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "d311a800-d573-4b2e-b880-2993cef767c2");
user_pref("security.sandbox.plugin.tempDirSuffix", "43437b5c-911a-40a8-b92b-75b5e0011b79");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("toolkit.startup.last_success", 1580924259);
user_pref("toolkit.telemetry.cachedClientID", "e4d9695b-0280-4cdb-a9c1-1bc4fb31ea00");
user_pref("toolkit.telemetry.previousBuildID", "20200117190643");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
