// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupRolloutPrefs.browser.toolbars.bookmarks.2h2020", true);
user_pref("app.normandy.startupRolloutPrefs.network.preload", true);
user_pref("app.normandy.user_id", "e5b5736c-d3e4-48e9-a3ec-007681d6a427");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1611362852);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1611362850);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.ctrlTab.previews", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1611362847);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 104);
user_pref("browser.newtabpage.activity-stream.impressionId", "{6a63483d-f6dc-40cb-8f03-d70e5068d179}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1611362851627");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1611384451627");
user_pref("browser.search.region", "SG");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1611362850");
user_pref("browser.slowStartup.averageTime", 2913);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20210105180113");
user_pref("browser.startup.homepage_override.mstone", "84.0.2");
user_pref("browser.startup.homepage_override.once", "{\"message_id\":\"WNP_MOMENTS_4\",\"url\":\"https://www.mozilla.org/firefox/welcome/4/\",\"expire\":1611967651882}");
user_pref("browser.startup.lastColdStartupCheck", 1611362848);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1611362852776");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "84.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "2c116863cd87494f84bd39822317e31c");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "84.0.2");
user_pref("extensions.lastPlatformVersion", "84.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"38ca6889-cd8c-4295-a049-b5562e92035c\",\"formautofill@mozilla.org\":\"c2680fc0-b01f-4971-89bf-8496b6d1e40e\",\"screenshots@mozilla.org\":\"596a54e8-c0d9-4b44-a79b-ebf0afe5d5a0\",\"webcompat-reporter@mozilla.org\":\"946853dd-654f-47c1-a7b1-883c789ced5a\",\"webcompat@mozilla.org\":\"4052e7db-4caf-48a0-9e28-88f68335cacb\",\"default-theme@mozilla.org\":\"47f8d91b-3944-49d9-811e-91a62da67182\",\"google@search.mozilla.org\":\"9d16488f-7004-4593-bda6-b328145133ef\",\"amazondotcom@search.mozilla.org\":\"d27798dd-2c05-41a7-8ca9-58bf226d92d9\",\"wikipedia@search.mozilla.org\":\"faa4ed02-41b8-4a19-b562-fb806073ab9d\",\"bing@search.mozilla.org\":\"2f9295e2-74fd-41a1-a53b-42be932b8ff7\",\"ddg@search.mozilla.org\":\"64e37b65-0456-4d71-ba9c-dbcab2e4cff6\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.state.flash", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "dd66e10d-b0a7-4f51-824b-a05694ccbe50");
user_pref("security.sandbox.plugin.tempDirSuffix", "c8b42c76-9276-433b-a4e8-8c69384633ef");
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("toolkit.startup.last_success", 1611362845);
user_pref("toolkit.telemetry.cachedClientID", "766699a5-95bd-4041-80e0-40026a83f3d7");
user_pref("toolkit.telemetry.previousBuildID", "20210105180113");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
