// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.startupRolloutPrefs.services.sync.engine.bookmarks.buffer", true);
user_pref("app.normandy.user_id", "0ddd4ccb-341b-4000-bc74-6de637bb3556");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1578157061);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1578157181);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1578157421);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1578156821);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1578156701);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1578156941);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1578153415);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1578157301);
user_pref("browser.cache.disk.amount_written", 0);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.ctrlTab.previews", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1578153356);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 87);
user_pref("browser.newtabpage.activity-stream.impressionId", "{960fdbd2-b7b5-4aba-b7a8-b652b0a504fc}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1578158530098");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1578160342098");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1578156959427");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1578160559427");
user_pref("browser.search.region", "SG");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20191205184924");
user_pref("browser.slowStartup.averageTime", 1191);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20191205184924");
user_pref("browser.startup.homepage_override.mstone", "71.0");
user_pref("browser.startup.lastColdStartupCheck", 1578157830);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1578153359894");
user_pref("distribution.iniFile.exists.appversion", "71.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.peppermint.bookmarksProcessed", true);
user_pref("dom.push.userAgentID", "d22a092bc63f4708b0f358b16a0e7323");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Fri, 03 Jan 2020 20:47:46 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1578157062);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20191205184924");
user_pref("extensions.lastAppVersion", "71.0");
user_pref("extensions.lastPlatformVersion", "71.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"66df084f-0eea-43d8-af3b-3f4062c9bdad\",\"screenshots@mozilla.org\":\"a5049d8d-d443-4f7b-a1f0-3f9ad1ecef36\",\"webcompat-reporter@mozilla.org\":\"9b83fffe-1119-4df7-a479-46e8e6578c78\",\"webcompat@mozilla.org\":\"e4dfc6d4-76d7-4163-8a3b-30cce27eadde\",\"default-theme@mozilla.org\":\"c1196a2b-d2d9-4ba2-ac95-7b59a5cebfa3\",\"google@search.mozilla.org\":\"f872b33b-b094-4263-8b9e-04778925a811\",\"amazondotcom@search.mozilla.org\":\"41eed3ac-e2e1-431f-8866-fea5e99735cf\",\"bing@search.mozilla.org\":\"091aac1e-0a66-4660-9af5-a8d7aea5f7a6\",\"ddg@search.mozilla.org\":\"886dc54c-a80b-4725-bf6e-d240cffeab94\",\"ebay@search.mozilla.org\":\"4365fbe5-ba7d-4050-9810-ed842fec6509\",\"twitter@search.mozilla.org\":\"1abb568c-28c1-40a9-892a-a00156530430\",\"wikipedia@search.mozilla.org\":\"0842030b-841b-4b03-99e1-60b71f5e9de4\"}");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1578157063);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20191205184924");
user_pref("media.gmp-manager.lastCheck", 1578157209);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.state.flash", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "40d48931-b3df-4fdc-b94f-b84327134fc9");
user_pref("security.sandbox.plugin.tempDirSuffix", "195384bf-68fd-4eb5-839f-259467eab7d9");
user_pref("services.blocklist.pinning.checked", 1578157209);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1578096077172\"");
user_pref("services.settings.last_update_seconds", 1578157209);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1578157209);
user_pref("services.settings.main.cfr-fxa.last_check", 1578157209);
user_pref("services.settings.main.cfr.last_check", 1578157209);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1578157209);
user_pref("services.settings.main.hijack-blocklists.last_check", 1578157209);
user_pref("services.settings.main.language-dictionaries.last_check", 1578157209);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1578157209);
user_pref("services.settings.main.public-suffix-list.last_check", 1578157209);
user_pref("services.settings.main.sites-classification.last_check", 1578157209);
user_pref("services.settings.main.tippytop.last_check", 1578157209);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1578157209);
user_pref("services.settings.main.whats-new-panel.last_check", 1578157209);
user_pref("services.settings.security.onecrl.checked", 1578157209);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("toolkit.startup.last_success", 1578157829);
user_pref("toolkit.telemetry.cachedClientID", "9b9762f9-5322-4da3-bb0b-853e81c478e5");
user_pref("toolkit.telemetry.previousBuildID", "20191205184924");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
