// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "6007d25c-acfb-410c-bd1d-c8dc2671d017");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1612585325);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1612585322);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.ctrlTab.previews", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1612585320);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 104);
user_pref("browser.newtabpage.activity-stream.impressionId", "{caa9bf9b-01c7-40cb-8a1f-3fc733b941b7}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.region.update.updated", 1612585322);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1612585324666");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1612606924666");
user_pref("browser.search.region", "SG");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1612585322");
user_pref("browser.slowStartup.averageTime", 2801);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20210118153634");
user_pref("browser.startup.homepage_override.mstone", "85.0");
user_pref("browser.startup.homepage_override.once", "{\"message_id\":\"WNP_MOMENTS_4\",\"url\":\"https://www.mozilla.org/firefox/welcome/4/\",\"expire\":1613190124477}");
user_pref("browser.startup.lastColdStartupCheck", 1612585321);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1612585325281");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "85.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "0b44c35ad5fb4ac583366eb372554161");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210118153634");
user_pref("extensions.lastAppVersion", "85.0");
user_pref("extensions.lastPlatformVersion", "85.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"7b580942-4d82-4f25-a4ae-a3657fc6b52f\",\"formautofill@mozilla.org\":\"acc6cba3-9b5f-4dd5-a95d-e6e3208f79e4\",\"screenshots@mozilla.org\":\"bc3627dc-0b9d-42e9-a14b-36298777c53f\",\"webcompat-reporter@mozilla.org\":\"442800ea-0125-4c21-87b8-41aa25cce542\",\"webcompat@mozilla.org\":\"0304365d-b48b-415b-b382-d528b12e1ada\",\"default-theme@mozilla.org\":\"96363fff-5157-4889-a759-c840782d4bd5\",\"google@search.mozilla.org\":\"73c501fe-9ff1-406b-9208-adb36aa6659b\",\"amazondotcom@search.mozilla.org\":\"073b529f-9f97-4184-a291-4db82b45a5c5\",\"wikipedia@search.mozilla.org\":\"9b2c24d8-dcb9-4ceb-bb58-c6c998419785\",\"bing@search.mozilla.org\":\"42716d9c-4670-4a94-9120-ffd3d3bdfebf\",\"ddg@search.mozilla.org\":\"f96e497c-6274-4df9-8b67-8629513b2c91\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("plugin.state.flash", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "4e5675af-c2ef-4794-b3b3-8eb91fd45000");
user_pref("security.sandbox.plugin.tempDirSuffix", "119f481c-965a-48bb-869c-fe02787b744c");
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("toolkit.startup.last_success", 1612585317);
user_pref("toolkit.telemetry.cachedClientID", "8285de05-49ef-4b1b-9a2c-314568a8200a");
user_pref("toolkit.telemetry.previousBuildID", "20210118153634");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
