// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupExperimentPrefs.layout.css.font-visibility.level", 2);
user_pref("app.normandy.startupRolloutPrefs.network.dns.dns_query_single_label", false);
user_pref("app.normandy.user_id", "d6800caa-c0a8-46f9-9335-2ace632631b1");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1606710262);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1606710330);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.ctrlTab.previews", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1606710258);
user_pref("browser.laterrun.bookkeeping.sessionCount", 5);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 102);
user_pref("browser.newtabpage.activity-stream.impressionId", "{c0b0b6ff-3b5a-4093-989e-5daf1214315f}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1606710261463");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1606731861463");
user_pref("browser.search.region", "SG");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20201112153044");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1606710330");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20201112153044");
user_pref("browser.startup.homepage_override.mstone", "83.0");
user_pref("browser.startup.homepage_override.once", "{\"message_id\":\"WNP_MOMENTS_1\",\"url\":\"https://www.mozilla.org/firefox/welcome/1/\",\"expire\":1607315061186}");
user_pref("browser.startup.lastColdStartupCheck", 1606710330);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1606710262387");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "83.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "60ed49a6702a4558a37b272f4a1db30c");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20201112153044");
user_pref("extensions.lastAppVersion", "83.0");
user_pref("extensions.lastPlatformVersion", "83.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"3c1c2ecc-e414-4b7e-95ae-b6b449ff4e11\",\"formautofill@mozilla.org\":\"4ba1be3c-d234-4eea-a9aa-fa7b5bf3a71d\",\"screenshots@mozilla.org\":\"df1af905-83dc-41b7-bca1-2f48c3dfeace\",\"webcompat-reporter@mozilla.org\":\"a18dc527-151d-4ab4-8d28-cc2ce6906fb8\",\"webcompat@mozilla.org\":\"d000e630-a91a-4532-b19b-8d340cde28f5\",\"default-theme@mozilla.org\":\"54001c74-6ac8-4f45-b756-2ce1bf1f6c17\",\"google@search.mozilla.org\":\"9bc13fbe-86da-478e-9a52-301a3a3836a0\",\"amazondotcom@search.mozilla.org\":\"cf664ebc-d230-4862-9cce-cca659d23b54\",\"wikipedia@search.mozilla.org\":\"804a1f1f-1f7a-4983-8d33-bb00fd91291f\",\"bing@search.mozilla.org\":\"bfc4bb2f-a859-443f-8fd3-007bad99871f\",\"ddg@search.mozilla.org\":\"06c9c593-05a8-467b-acaf-72d3fc1a3c63\"}");
user_pref("font.internaluseonly.changed", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.state.flash", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "92725979-1a8f-406f-8366-ec40d5e2a42b");
user_pref("security.sandbox.plugin.tempDirSuffix", "d8c5282a-7e5e-4722-a7fd-47e315177fc6");
user_pref("signon.usage.hasEntry", false);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("toolkit.startup.last_success", 1606710328);
user_pref("toolkit.telemetry.cachedClientID", "247ac4c9-b1c5-4675-9966-2867c05e8f53");
user_pref("toolkit.telemetry.previousBuildID", "20201112153044");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
