// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "c547adc9-b551-4368-b6eb-604cd501e9ca");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1613801979);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1613801977);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.ctrlTab.previews", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1613801975);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 104);
user_pref("browser.newtabpage.activity-stream.impressionId", "{74dceac5-1745-4d9b-beb5-e9ac93807def}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.region.update.updated", 1613801977);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1613801978741");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1613823578741");
user_pref("browser.search.region", "SG");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1613801976");
user_pref("browser.slowStartup.averageTime", 2968);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20210204182252");
user_pref("browser.startup.homepage_override.mstone", "85.0.1");
user_pref("browser.startup.homepage_override.once", "{\"message_id\":\"WNP_MOMENTS_4\",\"url\":\"https://www.mozilla.org/firefox/welcome/4/\",\"expire\":1614406778594}");
user_pref("browser.startup.lastColdStartupCheck", 1613801976);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1613801979495");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "85.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "8a3371126f3d41879cb3ad08c95ebe0f");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210204182252");
user_pref("extensions.lastAppVersion", "85.0.1");
user_pref("extensions.lastPlatformVersion", "85.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"7f785915-9679-4956-9b91-edda88ca4365\",\"formautofill@mozilla.org\":\"713d89e8-8cac-4693-9ac6-2b44c202599a\",\"screenshots@mozilla.org\":\"4964c486-406f-4644-95b2-2aa7f015a591\",\"webcompat-reporter@mozilla.org\":\"407b7f94-c5f5-4f53-bfeb-e05b917d84c0\",\"webcompat@mozilla.org\":\"a0069b84-99fe-406e-85db-04a231ec74f6\",\"default-theme@mozilla.org\":\"f1dc82a5-4a19-45d9-95c9-a92448465a53\",\"google@search.mozilla.org\":\"a1be8b68-2e07-4f48-ba05-b5fcc5f5e178\",\"amazondotcom@search.mozilla.org\":\"e8b0ac9c-4b15-4291-8538-6a6f9dfff724\",\"wikipedia@search.mozilla.org\":\"0ce1747e-0f4c-4e8b-8200-262744a8bb15\",\"bing@search.mozilla.org\":\"451fa0b3-4839-43bf-b44e-086b2bd438e2\",\"ddg@search.mozilla.org\":\"27619b21-f765-44c3-ada4-52a2d6fefc22\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("plugin.state.flash", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "e0e32a4a-1d76-46b7-a89c-8eadf664505a");
user_pref("security.sandbox.plugin.tempDirSuffix", "cdfd5b23-b86c-48e8-901d-55307f0408c7");
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("toolkit.startup.last_success", 1613801972);
user_pref("toolkit.telemetry.cachedClientID", "c74fbd7b-2285-43fb-b99b-a45e6b3ae97e");
user_pref("toolkit.telemetry.previousBuildID", "20210204182252");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
